// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SGS.HN.Labeler.Repository.Models;

public partial class LIMS20_UATContext : DbContext
{
    public LIMS20_UATContext(DbContextOptions<LIMS20_UATContext> options)
        : base(options)
    {
    }

    public virtual DbSet<OrdSl> OrdSls { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<OrdSl>(entity =>
        {
            entity.ToTable("ORD_SL", tb =>
                {
                    tb.HasComment("訂單樣品服務線資料");
                    tb.HasTrigger("TRI_ORD_SL");
                    tb.HasTrigger("TRI_ORD_SL_BATCHID");
                    tb.HasTrigger("TRI_ORD_SL_BATCH_JOB");
                    tb.HasTrigger("TRI_ORD_SL_TRAN_STATE");
                    tb.HasTrigger("TRI_ORD_SL_TS_METH_VER");
                });

            entity.HasIndex(e => new { e.DataState, e.OrdMid, e.OrdSid }, "IX_ORD_SL_20191108_2");

            entity.HasIndex(e => e.LabId, "IX_ORD_SL_20200516_02");

            entity.HasIndex(e => new { e.OrdMid, e.SlWfCode }, "IX_ORD_SL_20200805_01");

            entity.HasIndex(e => new { e.OrdMid, e.SlWfCode, e.DataState }, "IX_ORD_SL_20200825_01");

            entity.HasIndex(e => e.OrdMid, "IX_ORD_SL_20200826_01");

            entity.HasIndex(e => new { e.OrdMid, e.DataState, e.SlWfCode }, "IX_ORD_SL_20200903_01");

            entity.HasIndex(e => new { e.DataState, e.OrdMid }, "IX_ORD_SL_20200903_02");

            entity.HasIndex(e => new { e.OrdSid, e.SlWfCode }, "IX_ORD_SL_20200915_03");

            entity.HasIndex(e => new { e.OrdSid, e.DataState }, "IX_ORD_SL_20210928_1");

            entity.HasIndex(e => e.BatchId, "IX_ORD_SL_20211208_01");

            entity.HasIndex(e => new { e.LabId, e.DataState }, "IX_ORD_SL_20211217_01");

            entity.HasIndex(e => new { e.DataState, e.OrdSlid, e.OrdSid }, "IX_ORD_SL_20211219_01");

            entity.HasIndex(e => e.SampGpId, "IX_ORD_SL_20211227_01");

            entity.HasIndex(e => new { e.LabId, e.DataState, e.SmpReciYn }, "IX_ORD_SL_20220321_01");

            entity.HasIndex(e => new { e.OrdMid, e.OrdSid, e.OrdSlid, e.SampGpId, e.DataState }, "IX_ORD_SL_20220629_01");

            entity.Property(e => e.OrdSlid)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasComment("訂單樣品服務線編號")
                .HasColumnName("ORD_SLID");
            entity.Property(e => e.AreaFrom)
                .HasMaxLength(10)
                .HasComment("訂單開立所屬地區別代號(代碼AREA_CODE)")
                .HasColumnName("AREA_FROM");
            entity.Property(e => e.AreaTo)
                .HasMaxLength(10)
                .HasComment("此SL派工至哪一地區別代號(代碼AREA_CODE)")
                .HasColumnName("AREA_TO");
            entity.Property(e => e.BatchId)
                .HasMaxLength(14)
                .IsFixedLength()
                .HasComment("批次ID")
                .HasColumnName("BATCH_ID");
            entity.Property(e => e.BatchIxNo)
                .HasComment("批次序號")
                .HasColumnName("BATCH_IX_NO");
            entity.Property(e => e.CrtDate)
                .HasDefaultValueSql("(getdate())")
                .HasComment("建檔日期")
                .HasColumnType("datetime")
                .HasColumnName("CRT_DATE");
            entity.Property(e => e.CrtUser)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("建檔人員 ID")
                .HasColumnName("CRT_USER");
            entity.Property(e => e.DataState)
                .IsRequired()
                .HasMaxLength(1)
                .IsFixedLength()
                .HasComment("訂單狀態")
                .HasColumnName("DATA_STATE");
            entity.Property(e => e.GrpId)
                .HasMaxLength(7)
                .IsFixedLength()
                .HasComment("群組 ID")
                .HasColumnName("GRP_ID");
            entity.Property(e => e.IxNo)
                .HasComment("流水號")
                .HasColumnName("IX_NO");
            entity.Property(e => e.LabId)
                .HasMaxLength(20)
                .HasComment("實驗室 ID")
                .HasColumnName("LAB_ID");
            entity.Property(e => e.MatId)
                .HasMaxLength(9)
                .IsFixedLength()
                .HasComment("基質 ID")
                .HasColumnName("MAT_ID");
            entity.Property(e => e.MdfDate)
                .HasComment("修改日期")
                .HasColumnType("datetime")
                .HasColumnName("MDF_DATE");
            entity.Property(e => e.MdfUser)
                .HasMaxLength(50)
                .HasComment("修改人員 ID")
                .HasColumnName("MDF_USER");
            entity.Property(e => e.OrdMid)
                .IsRequired()
                .HasMaxLength(20)
                .HasComment("訂單編號")
                .HasColumnName("ORD_MID");
            entity.Property(e => e.OrdMidFrom)
                .HasMaxLength(20)
                .HasComment("(TFDA訂單)來源訂單編號")
                .HasColumnName("ORD_MID_FROM");
            entity.Property(e => e.OrdSid)
                .IsRequired()
                .HasMaxLength(17)
                .IsFixedLength()
                .HasComment("訂單樣品編號")
                .HasColumnName("ORD_SID");
            entity.Property(e => e.OrdSidFrom)
                .HasMaxLength(17)
                .IsFixedLength()
                .HasComment("(TFDA訂單)來源訂單樣品編號")
                .HasColumnName("ORD_SID_FROM");
            entity.Property(e => e.OrdSlidFrom)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasComment("(TFDA訂單)來源訂單樣品服務線編號")
                .HasColumnName("ORD_SLID_FROM");
            entity.Property(e => e.OrdSlidSrc)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasComment("(延伸號訂單)來源訂單樣品服務線編號")
                .HasColumnName("ORD_SLID_SRC");
            entity.Property(e => e.PpId)
                .HasMaxLength(9)
                .IsFixedLength()
                .HasComment("套裝商品 ID")
                .HasColumnName("PP_ID");
            entity.Property(e => e.PpNm)
                .HasMaxLength(150)
                .HasComment("套裝測試項目名稱")
                .HasColumnName("PP_NM");
            entity.Property(e => e.QcIxNo)
                .HasComment("品保序號")
                .HasColumnName("QC_IX_NO");
            entity.Property(e => e.RegId)
                .HasMaxLength(9)
                .IsFixedLength()
                .HasComment("規範 ID")
                .HasColumnName("REG_ID");
            entity.Property(e => e.RegVer)
                .HasComment("版本")
                .HasColumnName("REG_VER");
            entity.Property(e => e.RptGrpId)
                .HasMaxLength(11)
                .HasComment("報告預選群組ID")
                .HasColumnName("RPT_GRP_ID");
            entity.Property(e => e.SampGpId)
                .HasMaxLength(11)
                .IsFixedLength()
                .HasComment("採樣群組 ID")
                .HasColumnName("SAMP_GP_ID");
            entity.Property(e => e.SlDiscAmt)
                .HasComment("折扣金額")
                .HasColumnType("decimal(21, 6)")
                .HasColumnName("SL_DISC_AMT");
            entity.Property(e => e.SlDiscPerc)
                .HasComment("折扣%")
                .HasColumnName("SL_DISC_PERC");
            entity.Property(e => e.SlId)
                .IsRequired()
                .HasMaxLength(11)
                .IsFixedLength()
                .HasComment("服務線 ID")
                .HasColumnName("SL_ID");
            entity.Property(e => e.SlIdLab)
                .HasMaxLength(11)
                .IsFixedLength()
                .HasComment("服務項ID(LAB挑選)")
                .HasColumnName("SL_ID_LAB");
            entity.Property(e => e.SlOrigPrice)
                .HasComment("原始售價")
                .HasColumnType("decimal(21, 6)")
                .HasColumnName("SL_ORIG_PRICE");
            entity.Property(e => e.SlPrice)
                .HasComment("定價")
                .HasColumnType("decimal(21, 6)")
                .HasColumnName("SL_PRICE");
            entity.Property(e => e.SlPriceCurr)
                .HasMaxLength(20)
                .HasComment("幣別")
                .HasColumnName("SL_PRICE_CURR");
            entity.Property(e => e.SlQty)
                .HasComment("單位量")
                .HasColumnName("SL_QTY");
            entity.Property(e => e.SlSubtotal)
                .HasComment("小計")
                .HasColumnType("decimal(21, 6)")
                .HasColumnName("SL_SUBTOTAL");
            entity.Property(e => e.SlTotal)
                .HasComment("實際售價")
                .HasColumnType("decimal(21, 6)")
                .HasColumnName("SL_TOTAL");
            entity.Property(e => e.SlVer)
                .HasComment("版本")
                .HasColumnName("SL_VER");
            entity.Property(e => e.SlVerLab)
                .HasComment("版本(LAB挑選)")
                .HasColumnName("SL_VER_LAB");
            entity.Property(e => e.SlWfCode)
                .HasComment("服務線進度(代碼ORD_SL_STATUS)")
                .HasColumnName("SL_WF_CODE");
            entity.Property(e => e.SmpClrYn)
                .HasComment("已清除")
                .HasColumnName("SMP_CLR_YN");
            entity.Property(e => e.SmpPrtQty)
                .HasComment("列印數量")
                .HasColumnName("SMP_PRT_QTY");
            entity.Property(e => e.SmpReciYn)
                .HasComment("已收樣")
                .HasColumnName("SMP_RECI_YN");
            entity.Property(e => e.SmpRtnYn)
                .HasComment("已退樣")
                .HasColumnName("SMP_RTN_YN");
            entity.Property(e => e.SmpTakDate)
                .HasComment("取樣日期")
                .HasColumnType("datetime")
                .HasColumnName("SMP_TAK_DATE");
            entity.Property(e => e.SmpTakQty)
                .HasMaxLength(50)
                .HasComment("取樣量")
                .HasColumnName("SMP_TAK_QTY");
            entity.Property(e => e.SmpTakYn)
                .HasComment("已取樣")
                .HasColumnName("SMP_TAK_YN");
            entity.Property(e => e.TeamId)
                .HasMaxLength(8)
                .IsFixedLength()
                .HasComment("組別 ID")
                .HasColumnName("TEAM_ID");
            entity.Property(e => e.TransState)
                .HasMaxLength(20)
                .HasComment("打包狀態(代碼TRANS_STATE)")
                .HasColumnName("TRANS_STATE");
            entity.Property(e => e.TsCod)
                .HasMaxLength(150)
                .HasComment("測試條件")
                .HasColumnName("TS_COD");
            entity.Property(e => e.TsItemAmt)
                .HasMaxLength(60)
                .HasComment("(結帳總計用)")
                .HasColumnName("TS_ITEM_AMT");
            entity.Property(e => e.TsItemYn)
                .HasComment("(結帳總計用)")
                .HasColumnName("TS_ITEM_YN");
            entity.Property(e => e.TsMethId)
                .HasMaxLength(11)
                .IsFixedLength()
                .HasComment("測試方法 ID")
                .HasColumnName("TS_METH_ID");
            entity.Property(e => e.TsMethVer)
                .HasComment("測試方法版本")
                .HasColumnName("TS_METH_VER");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}