// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGS.HN.Labeler.Repository.Models;

/// <summary>
/// 訂單樣品服務線資料
/// </summary>
public partial class OrdSl
{
    /// <summary>
    /// 訂單樣品服務線編號
    /// </summary>
    public string OrdSlid { get; set; }

    /// <summary>
    /// (延伸號訂單)來源訂單樣品服務線編號
    /// </summary>
    public string OrdSlidSrc { get; set; }

    /// <summary>
    /// (TFDA訂單)來源訂單樣品服務線編號
    /// </summary>
    public string OrdSlidFrom { get; set; }

    /// <summary>
    /// 訂單編號
    /// </summary>
    public string OrdMid { get; set; }

    /// <summary>
    /// (TFDA訂單)來源訂單編號
    /// </summary>
    public string OrdMidFrom { get; set; }

    /// <summary>
    /// 訂單樣品編號
    /// </summary>
    public string OrdSid { get; set; }

    /// <summary>
    /// (TFDA訂單)來源訂單樣品編號
    /// </summary>
    public string OrdSidFrom { get; set; }

    /// <summary>
    /// 套裝商品 ID
    /// </summary>
    public string PpId { get; set; }

    /// <summary>
    /// 套裝測試項目名稱
    /// </summary>
    public string PpNm { get; set; }

    /// <summary>
    /// 服務線 ID
    /// </summary>
    public string SlId { get; set; }

    /// <summary>
    /// 版本
    /// </summary>
    public int SlVer { get; set; }

    /// <summary>
    /// 流水號
    /// </summary>
    public int IxNo { get; set; }

    /// <summary>
    /// 實驗室 ID
    /// </summary>
    public string LabId { get; set; }

    /// <summary>
    /// 規範 ID
    /// </summary>
    public string RegId { get; set; }

    /// <summary>
    /// 版本
    /// </summary>
    public int? RegVer { get; set; }

    /// <summary>
    /// 基質 ID
    /// </summary>
    public string MatId { get; set; }

    /// <summary>
    /// 測試條件
    /// </summary>
    public string TsCod { get; set; }

    /// <summary>
    /// 測試方法 ID
    /// </summary>
    public string TsMethId { get; set; }

    /// <summary>
    /// 定價
    /// </summary>
    public decimal SlPrice { get; set; }

    /// <summary>
    /// 原始售價
    /// </summary>
    public decimal? SlOrigPrice { get; set; }

    /// <summary>
    /// 幣別
    /// </summary>
    public string SlPriceCurr { get; set; }

    /// <summary>
    /// 單位量
    /// </summary>
    public int? SlQty { get; set; }

    /// <summary>
    /// 折扣%
    /// </summary>
    public short? SlDiscPerc { get; set; }

    /// <summary>
    /// 小計
    /// </summary>
    public decimal? SlSubtotal { get; set; }

    /// <summary>
    /// 折扣金額
    /// </summary>
    public decimal? SlDiscAmt { get; set; }

    /// <summary>
    /// 實際售價
    /// </summary>
    public decimal? SlTotal { get; set; }

    /// <summary>
    /// (結帳總計用)
    /// </summary>
    public bool? TsItemYn { get; set; }

    /// <summary>
    /// (結帳總計用)
    /// </summary>
    public string TsItemAmt { get; set; }

    /// <summary>
    /// 群組 ID
    /// </summary>
    public string GrpId { get; set; }

    /// <summary>
    /// 組別 ID
    /// </summary>
    public string TeamId { get; set; }

    /// <summary>
    /// 批次ID
    /// </summary>
    public string BatchId { get; set; }

    /// <summary>
    /// 服務線進度(代碼ORD_SL_STATUS)
    /// </summary>
    public short SlWfCode { get; set; }

    /// <summary>
    /// 訂單狀態
    /// </summary>
    public string DataState { get; set; }

    /// <summary>
    /// 訂單開立所屬地區別代號(代碼AREA_CODE)
    /// </summary>
    public string AreaFrom { get; set; }

    /// <summary>
    /// 此SL派工至哪一地區別代號(代碼AREA_CODE)
    /// </summary>
    public string AreaTo { get; set; }

    /// <summary>
    /// 打包狀態(代碼TRANS_STATE)
    /// </summary>
    public string TransState { get; set; }

    /// <summary>
    /// 建檔日期
    /// </summary>
    public DateTime CrtDate { get; set; }

    /// <summary>
    /// 建檔人員 ID
    /// </summary>
    public string CrtUser { get; set; }

    /// <summary>
    /// 修改日期
    /// </summary>
    public DateTime? MdfDate { get; set; }

    /// <summary>
    /// 修改人員 ID
    /// </summary>
    public string MdfUser { get; set; }

    /// <summary>
    /// 測試方法版本
    /// </summary>
    public int? TsMethVer { get; set; }

    /// <summary>
    /// 採樣群組 ID
    /// </summary>
    public string SampGpId { get; set; }

    /// <summary>
    /// 批次序號
    /// </summary>
    public int? BatchIxNo { get; set; }

    /// <summary>
    /// 品保序號
    /// </summary>
    public int? QcIxNo { get; set; }

    /// <summary>
    /// 已收樣
    /// </summary>
    public bool SmpReciYn { get; set; }

    /// <summary>
    /// 已退樣
    /// </summary>
    public bool SmpRtnYn { get; set; }

    /// <summary>
    /// 已取樣
    /// </summary>
    public bool SmpTakYn { get; set; }

    /// <summary>
    /// 取樣日期
    /// </summary>
    public DateTime? SmpTakDate { get; set; }

    /// <summary>
    /// 取樣量
    /// </summary>
    public string SmpTakQty { get; set; }

    /// <summary>
    /// 已清除
    /// </summary>
    public bool SmpClrYn { get; set; }

    /// <summary>
    /// 列印數量
    /// </summary>
    public int? SmpPrtQty { get; set; }

    /// <summary>
    /// 服務項ID(LAB挑選)
    /// </summary>
    public string SlIdLab { get; set; }

    /// <summary>
    /// 版本(LAB挑選)
    /// </summary>
    public int? SlVerLab { get; set; }

    /// <summary>
    /// 報告預選群組ID
    /// </summary>
    public string RptGrpId { get; set; }
}